# Site settings
title: Unreal Easy Injector
description: > # this means to break the line
  User-friendly app that lets you play standard PC Unreal engine games in virtual reality using UEVR.
url: "https://www.uevrdeluxe.org" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman

# Author settings
author:
  name: Oliver Duis

# Social settings
social:
  github: oduis

# Plugins
plugins:
  - jekyll-seo-tag

# Navigation settings
navigation:
  - title: "Home"
    url: "/index"
  - title: "UEVR tutorial"
    url: "/UEVRTutorial"
  - title: "Submit profile"
    url: "/SubmitProfile"

